<?php

/**
 * @file
 * Contains helhist_admin_forms.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function helhist_admin_forms_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the helhist_admin_forms module.
    case 'help.page.helhist_admin_forms':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides customizations for admin forms') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helhist_admin_forms_form_node_form_alter(&$form, &$form_state, $form_id) {
  if (in_array($form_id, [
    'node_article_edit_form',
    'node_article_form',
    'node_listing_page_edit_form',
    'node_listing_page_form'
  ])) {
    // Control Hero paragraph visibility via checkbox states.
    $form['field_hero']['#states'] = [
      'visible' => [
        ':input[name="field_has_hero[value]"]' => ['checked' => TRUE],
      ],
    ];
  }
  
  if (in_array($form_id, [
    'node_listing_page_edit_form',
    'node_listing_page_form'
  ])) {
    // Control Phenomena field visibility via Listing type selection.
    $form['field_phenomena']['#states'] = [
      'visible' => [
        ':input[name="field_listing_type"]' => ['value' => 'article'],
      ],
      'required' => [
        ':input[name="field_listing_type"]' => ['value' => 'article'],
      ],
    ];
  }
}
